-- SQLite
-- 02- Creation Tables

CREATE TABLE PRODUCTS (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
CODE VARCHAR (25) NOT NULL,
NAME VARCHAR(25) NOT NULL,
PRICE FLOAT DEFAULT 0.0,
ENTRY_DATE DATE DEFAULT CURRENT_DATE,
BRAND VARCHAR(25) NOT NULL,
STOCK_AVAILABLE INTEGER DEFAULT 0
);

CREATE TABLE SHOPPING_CART (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
BUYER_EMAIL VARCHAR(25) NOT NULL
);

CREATE TABLE INVOICES (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
INVOICE_NUMBER INTEGER NOT NULL,
PURCHASE_DATE DATE DEFAULT CURRENT_DATE,
BUYER_EMAIL VARCHAR(25) NOT NULL,
TOTAL_AMOUNT FLOAT DEFAULT 0.0
);

CREATE TABLE SHOPPING_CART_PRODUCTS (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
SHOPPINGCART_ID INTEGER REFERENCES SHOPPING_CART(ID),
PRODUCT_ID INTEGER REFERENCES PRODUCTS(ID),
QUANTITY INTEGER DEFAULT 0
);

CREATE TABLE INVOICE_PRODUCTS (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
INVOICE_ID INTEGER REFERENCES INVOICES(ID),
PRODUCT_ID INTEGER REFERENCES PRODUCTS(ID),
QUANTITY INTEGER DEFAULT 0,
TOTAL_AMOUNT FLOAT DEFAULT 0.0
);

-- 03-Alter Tables

ALTER TABLE INVOICES
ADD PHONE_NUMBER TEXT NOT NULL DEFAULT '00000000';

ALTER TABLE INVOICES
ADD EMPLOYEE_CODE TEXT NOT NULL DEFAULT '0000000000';


-- Insert data

INSERT INTO PRODUCTS
(CODE, NAME, PRICE, BRAND, STOCK_AVAILABLE)
VALUES
('P001', 'Laptop HP', 850000, 'HP', 10),
('P002', 'Mouse Logitech', 25000, 'Logitech', 50),
('P003', 'Monitor Samsung', 180000, 'Samsung', 15),
('P004', 'Teclado Redragon', 45000, 'Redragon', 20),
('P005', 'Disco SSD 1TB', 120000, 'Kingston', 30),
('P006', 'Impresora Epson', 220000, 'Epson', 8),
('P007', 'Webcam HD', 35000, 'Logitech', 25),
('P008', 'Tablet Lenovo', 280000, 'Lenovo', 12);

INSERT INTO SHOPPING_CART
(BUYER_EMAIL)
VALUES
('miguel@gmail.com'),
('ana@gmail.com'),
('carlos@gmail.com'),
('miguel@gmail.com');

INSERT INTO INVOICES
(
INVOICE_NUMBER,
BUYER_EMAIL,
TOTAL_AMOUNT,
PHONE_NUMBER,
EMPLOYEE_CODE
)
VALUES
(1001, 'miguel@gmail.com', 1070000, '88881111', 'EMP001'),
(1002, 'ana@gmail.com', 180000, '88882222', 'EMP002'),
(1003, 'miguel@gmail.com', 265000, '88881111', 'EMP001'),
(1004, 'carlos@gmail.com', 850000, '88883333', 'EMP003');

INSERT INTO SHOPPING_CART_PRODUCTS_NEW
(
SHOPPINGCART_ID,
PRODUCT_ID,
QUANTITY
)
VALUES
(1, 1, 1),
(1, 2, 2),
(2, 3, 1),
(2, 4, 2),
(3, 5, 1),
(3, 7, 3),
(4, 6, 1),
(4, 8, 2);

INSERT INTO INVOICE_PRODUCTS_NEW
(
INVOICE_ID,
PRODUCT_ID,
QUANTITY,
TOTAL_AMOUNT
)
VALUES
(1, 1, 1, 850000),
(1, 5, 1, 120000),
(1, 6, 1, 220000),
(2, 3, 1, 180000),
(3, 5, 1, 120000),
(3, 7, 1, 35000),
(3, 4, 2, 90000),
(4, 1, 1, 850000);

-- 04-Querys

-- 4.1- Obtenga todos los productos almacenados
SELECT * FROM PRODUCTS;

-- 4.2- Obtenga todos los productos que tengan un precio mayor a 50000
SELECT NAME, PRICE FROM PRODUCTS WHERE PRICE > 50000;

-- 4.3- Obtenga todas las compras de un mismo producto por id.
SELECT * FROM INVOICE_PRODUCTS WHERE PRODUCT_ID = 1;

-- 4.4- Obtenga todas las compras agrupadas por producto, donde se muestre el total comprado entre todas las compras.
SELECT PRODUCT_ID, SUM(QUANTITY) AS TOTAL_PURCHASED FROM INVOICE_PRODUCTS GROUP BY PRODUCT_ID;

-- 4.5- Obtenga todas las facturas realizadas por el mismo comprador
SELECT * FROM INVOICES WHERE BUYER_EMAIL = 'miguel@gmail.com';

-- 4.6- Obtenga todas las facturas ordenadas por monto total de forma descendente
SELECT * FROM INVOICES ORDER BY TOTAL_AMOUNT DESC;

-- 4.7- Obtenga una sola factura por número de factura.
SELECT * FROM INVOICES WHERE INVOICE_NUMBER = 1001;








